from tkinter import *
import datetime
now = datetime.datetime.now()
watertemp = 18
avglength = 60
fweight = 0.0065*avglength**(3.157)
def scircuit():
    errorlab.config(text="Short Circuit!!")
    flelab.config(background='red')
    flevar.config(background='red')
    fwelab.config(background='red')
    fwevar.config(background='red')
    wtemplab.config(background='red')
    wtempvar.config(background='red')
    datelab.config(background='red')
    datevar.config(background='red')
    timelab.config(background='red')
    w.config(background='red')
    erlab.config(background='red')
    errorlab.config(background='red')
    master.configure(background='red')
    master.after(1000, scircuitcolor)
def scircuitcolor():
    flelab.config(background='white')
    flevar.config(background='white')
    fwelab.config(background='white')
    fwevar.config(background='white')
    wtemplab.config(background='white')
    wtempvar.config(background='white')
    datelab.config(background='white')
    datevar.config(background='white')
    timelab.config(background='white')
    w.config(background='white')
    erlab.config(background='white')
    errorlab.config(background='white')
    master.configure(background='white')
    master.config(background='white')
    master.after(1000, scircuit)
master = Tk() 
flelab = Label(master, text='Fish Length:',  font=("Arial", 36))
flelab.grid(row=0) 
flevar = Label(master, text=(avglength,'cm'), font=("Arial", 36))
flevar.grid(row=0,column=1) 
fwelab = Label(master, text='Fish Weight:',  font=("Arial", 36))
fwelab.grid(row=1) 
fwevar = Label(master, text=(int(fweight),'grams'), font=("Arial", 36))
fwevar.grid(row=1,column=1)
wtemplab = Label(master, text='Water Temperature:',  font=("Arial", 36))
wtemplab.grid(row=2) 
wtempvar = Label(master, text=(watertemp,'C'), font=("Arial", 36))
wtempvar.grid(row=2,column=1)  
datelab= Label(master, text='Date:',  font=("Arial", 36))
datelab.grid(row=3)  
datevar = Label(master, text= now.strftime('%d/%m/%Y'), font=("Arial", 36))
datevar.grid(row=3,column=1)
timelab = Label(master, text='Time:', font=("Arial", 36))
timelab.grid(row=4,column=0)
w = Label(master, text= now.strftime("%H:%M:%S"), font=("Arial", 36))
w.grid(row=4,column=1)
erlab = Label(master, text='Errors:', font=("Arial", 36))
erlab.grid(row=5)
errorlab = Label(master, text='None',font=("Arial", 36))
errorlab.grid(row=5,column=1)
Button(master, text= 'Short!', command= scircuit).grid(row=6)
def clock():
    time = datetime.datetime.now().strftime("%H:%M:%S")
    w.config(text=time)
    master.after(1000, clock) # run itself again after 1000 ms

clock()
master.mainloop() 